services:
  postgres:
    image: postgres:18
    container_name: axum-db
    environment:
      POSTGRES_DB: axum-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    networks:
      - axum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d axum-db"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  axum-network:
    name: axum-network
    driver: bridge
